SolicitationManager_Ruby/config/routes.rb
SolicitationManager::Application.routes.draw do
  resources :terms

  resources :requirements

  resources :items

  root :to => 'home#index'
  
  resources :solicitations

  

end

SolicitationManager_Ruby/app/models/solicitation.rb
class Solicitation < ActiveRecord::Base
end

SolicitationManager_Ruby/app/controllers/solicitations_controller.rb
class SolicitationsController < ApplicationController
  before_action :set_solicitation, only: [:show, :edit, :update, :destroy]

  # GET /solicitations
  # GET /solicitations.json
  def index
    @solicitations = Solicitation.all
  end

  # GET /solicitations/1
  # GET /solicitations/1.json
  def show
  end

  # GET /solicitations/new
  def new
    @solicitation = Solicitation.new
  end

  # GET /solicitations/1/edit
  def edit
  end

  # POST /solicitations
  # POST /solicitations.json
  def create
    @solicitation = Solicitation.new(solicitation_params)

    respond_to do |format|
      if @solicitation.save
        format.html { redirect_to @solicitation, notice: 'Solicitation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @solicitation }
      else
        format.html { render action: 'new' }
        format.json { render json: @solicitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solicitations/1
  # PATCH/PUT /solicitations/1.json
  def update
    respond_to do |format|
      if @solicitation.update(solicitation_params)
        format.html { redirect_to @solicitation, notice: 'Solicitation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @solicitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solicitations/1
  # DELETE /solicitations/1.json
  def destroy
    @solicitation.destroy
    respond_to do |format|
      format.html { redirect_to solicitations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solicitation
      @solicitation = Solicitation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solicitation_params
      params.require(:solicitation).permit(:buy_num, :rev, :title, :buyer, :end_time, :set_aside_req, :location, :category, :subcategory, :naics, :fbo_solicitation, :recovery_act, :delivery, :bid_delivery_days, :repost_reason, :solicitation_num, :revised_at, :removed_at)
    end
end

SolicitationManager_Ruby/app/helpers/solicitations_helper.rb
module SolicitationsHelper
end

SolicitationManager_Ruby/app/views/solicitations/_form.html.erb
<%= form_for(@solicitation) do |f| %>
  <% if @solicitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@solicitation.errors.count, "error") %> prohibited this solicitation from being saved:</h2>

      <ul>
      <% @solicitation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :buy_num %><br>
    <%= f.text_field :buy_num %>
  </div>
  <div class="field">
    <%= f.label :rev %><br>
    <%= f.text_field :rev %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :buyer %><br>
    <%= f.text_field :buyer %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.text_field :end_time %>
  </div>
  <div class="field">
    <%= f.label :set_aside_req %><br>
    <%= f.text_field :set_aside_req %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :subcategory %><br>
    <%= f.text_field :subcategory %>
  </div>
  <div class="field">
    <%= f.label :naics %><br>
    <%= f.text_field :naics %>
  </div>
  <div class="field">
    <%= f.label :fbo_solicitation %><br>
    <%= f.text_field :fbo_solicitation %>
  </div>
  <div class="field">
    <%= f.label :recovery_act %><br>
    <%= f.text_field :recovery_act %>
  </div>
  <div class="field">
    <%= f.label :delivery %><br>
    <%= f.text_field :delivery %>
  </div>
  <div class="field">
    <%= f.label :bid_delivery_days %><br>
    <%= f.text_field :bid_delivery_days %>
  </div>
  <div class="field">
    <%= f.label :repost_reason %><br>
    <%= f.text_field :repost_reason %>
  </div>
  <div class="field">
    <%= f.label :solicitation_num %><br>
    <%= f.text_field :solicitation_num %>
  </div>
  <div class="field">
    <%= f.label :revised_at %><br>
    <%= f.text_field :revised_at %>
  </div>
  <div class="field">
    <%= f.label :removed_at %><br>
    <%= f.text_field :removed_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SolicitationManager_Ruby/app/views/solicitations/edit.html.erb
<h1>Editing solicitation</h1>

<%= render 'form' %>

<%= link_to 'Show', @solicitation %> |
<%= link_to 'Back', solicitations_path %>

SolicitationManager_Ruby/app/views/solicitations/index.html.erb
<h1>Listing solicitations</h1>

<table>
  <thead>
    <tr>
      <th>Buy num</th>
      <th>Rev</th>
      <th>Title</th>
      <th>Buyer</th>
      <th>End time</th>
      <th>Set aside req</th>
      <th>Location</th>
      <th>Category</th>
      <th>Subcategory</th>
      <th>Naics</th>
      <th>Fbo solicitation</th>
      <th>Recovery act</th>
      <th>Delivery</th>
      <th>Bid delivery days</th>
      <th>Repost reason</th>
      <th>Solicitation num</th>
      <th>Revised at</th>
      <th>Removed at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @solicitations.each do |solicitation| %>
      <tr>
        <td><%= solicitation.buy_num %></td>
        <td><%= solicitation.rev %></td>
        <td><%= solicitation.title %></td>
        <td><%= solicitation.buyer %></td>
        <td><%= solicitation.end_time %></td>
        <td><%= solicitation.set_aside_req %></td>
        <td><%= solicitation.location %></td>
        <td><%= solicitation.category %></td>
        <td><%= solicitation.subcategory %></td>
        <td><%= solicitation.naics %></td>
        <td><%= solicitation.fbo_solicitation %></td>
        <td><%= solicitation.recovery_act %></td>
        <td><%= solicitation.delivery %></td>
        <td><%= solicitation.bid_delivery_days %></td>
        <td><%= solicitation.repost_reason %></td>
        <td><%= solicitation.solicitation_num %></td>
        <td><%= solicitation.revised_at %></td>
        <td><%= solicitation.removed_at %></td>
        <td><%= link_to 'Show', solicitation %></td>
        <td><%= link_to 'Edit', edit_solicitation_path(solicitation) %></td>
        <td><%= link_to 'Destroy', solicitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Solicitation', new_solicitation_path %>

SolicitationManager_Ruby/app/views/solicitations/new.html.erb
<h1>New solicitation</h1>

<%= render 'form' %>

<%= link_to 'Back', solicitations_path %>

SolicitationManager_Ruby/app/views/solicitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Buy num:</strong>
  <%= @solicitation.buy_num %>
</p>

<p>
  <strong>Rev:</strong>
  <%= @solicitation.rev %>
</p>

<p>
  <strong>Title:</strong>
  <%= @solicitation.title %>
</p>

<p>
  <strong>Buyer:</strong>
  <%= @solicitation.buyer %>
</p>

<p>
  <strong>End time:</strong>
  <%= @solicitation.end_time %>
</p>

<p>
  <strong>Set aside req:</strong>
  <%= @solicitation.set_aside_req %>
</p>

<p>
  <strong>Location:</strong>
  <%= @solicitation.location %>
</p>

<p>
  <strong>Category:</strong>
  <%= @solicitation.category %>
</p>

<p>
  <strong>Subcategory:</strong>
  <%= @solicitation.subcategory %>
</p>

<p>
  <strong>Naics:</strong>
  <%= @solicitation.naics %>
</p>

<p>
  <strong>Fbo solicitation:</strong>
  <%= @solicitation.fbo_solicitation %>
</p>

<p>
  <strong>Recovery act:</strong>
  <%= @solicitation.recovery_act %>
</p>

<p>
  <strong>Delivery:</strong>
  <%= @solicitation.delivery %>
</p>

<p>
  <strong>Bid delivery days:</strong>
  <%= @solicitation.bid_delivery_days %>
</p>

<p>
  <strong>Repost reason:</strong>
  <%= @solicitation.repost_reason %>
</p>

<p>
  <strong>Solicitation num:</strong>
  <%= @solicitation.solicitation_num %>
</p>

<p>
  <strong>Revised at:</strong>
  <%= @solicitation.revised_at %>
</p>

<p>
  <strong>Removed at:</strong>
  <%= @solicitation.removed_at %>
</p>

<%= link_to 'Edit', edit_solicitation_path(@solicitation) %> |
<%= link_to 'Back', solicitations_path %>