PhantomCraigslistCrawler_Ruby/Version 2/config/routes.rb
MattsList::Application.routes.draw do
  root :to => 'home#index'
  resources :listings

  resources :searches

  resources :users

  

end

PhantomCraigslistCrawler_Ruby/Version 2/app/models/listing.rb
class Listing < ActiveRecord::Base
end

PhantomCraigslistCrawler_Ruby/Version 2/app/models/search.rb
class Search < ActiveRecord::Base
end

PhantomCraigslistCrawler_Ruby/Version 2/app/models/user.rb
class User < ActiveRecord::Base
end

PhantomCraigslistCrawler_Ruby/Version 2/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

PhantomCraigslistCrawler_Ruby/Version 2/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:userIDs, :cListNumber, :title, :price, :location, :date, :descriptionURL, :pictureURLs, :sellersEmail)
    end
end

PhantomCraigslistCrawler_Ruby/Version 2/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render action: 'show', status: :created, location: @search }
      else
        format.html { render action: 'new' }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:userIDs, :minPrice, :maxPrice, :keywords, :categoryURL, :listingIDs)
    end
end

PhantomCraigslistCrawler_Ruby/Version 2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstName, :lastName, :email, :homeURL, :subURL)
    end
end

PhantomCraigslistCrawler_Ruby/Version 2/app/helpers/home_helper.rb
module HomeHelper
end

PhantomCraigslistCrawler_Ruby/Version 2/app/helpers/listings_helper.rb
module ListingsHelper
end

PhantomCraigslistCrawler_Ruby/Version 2/app/helpers/searches_helper.rb
module SearchesHelper
end

PhantomCraigslistCrawler_Ruby/Version 2/app/helpers/users_helper.rb
module UsersHelper
end

PhantomCraigslistCrawler_Ruby/Version 2/app/views/home/index.html.erb
<h2>Hello, Matt!</h2>
<%= link_to "Users", users_path %>
</br></br>
<%= link_to 'Searches', searches_path %>
</br></br>
<%= link_to 'Listings', listings_path %>

PhantomCraigslistCrawler_Ruby/Version 2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MattsList</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

PhantomCraigslistCrawler_Ruby/Version 2/app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userIDs %><br>
    <%= f.text_field :userIDs %>
  </div>
  <div class="field">
    <%= f.label :cListNumber %><br>
    <%= f.text_field :cListNumber %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :descriptionURL %><br>
    <%= f.text_field :descriptionURL %>
  </div>
  <div class="field">
    <%= f.label :pictureURLs %><br>
    <%= f.text_area :pictureURLs %>
  </div>
  <div class="field">
    <%= f.label :sellersEmail %><br>
    <%= f.text_field :sellersEmail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PhantomCraigslistCrawler_Ruby/Version 2/app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

PhantomCraigslistCrawler_Ruby/Version 2/app/views/listings/index.html.erb
<h1>Listing listings</h1>

<table>
  <thead>
    <tr>
      <th>Userids</th>
      <th>Clistnumber</th>
      <th>Title</th>
      <th>Price</th>
      <th>Location</th>
      <th>Date</th>
      <th>Descriptionurl</th>
      <th>Pictureurls</th>
      <th>Sellersemail</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.userIDs %></td>
        <td><%= listing.cListNumber %></td>
        <td><%= listing.title %></td>
        <td><%= listing.price %></td>
        <td><%= listing.location %></td>
        <td><%= listing.date %></td>
        <td><%= listing.descriptionURL %></td>
        <td><%= listing.pictureURLs %></td>
        <td><%= listing.sellersEmail %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

PhantomCraigslistCrawler_Ruby/Version 2/app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

PhantomCraigslistCrawler_Ruby/Version 2/app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userids:</strong>
  <%= @listing.userIDs %>
</p>

<p>
  <strong>Clistnumber:</strong>
  <%= @listing.cListNumber %>
</p>

<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Location:</strong>
  <%= @listing.location %>
</p>

<p>
  <strong>Date:</strong>
  <%= @listing.date %>
</p>

<p>
  <strong>Descriptionurl:</strong>
  <%= @listing.descriptionURL %>
</p>

<p>
  <strong>Pictureurls:</strong>
  <%= @listing.pictureURLs %>
</p>

<p>
  <strong>Sellersemail:</strong>
  <%= @listing.sellersEmail %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

PhantomCraigslistCrawler_Ruby/Version 2/app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userIDs %><br>
    <%= f.text_field :userIDs %>
  </div>
  <div class="field">
    <%= f.label :minPrice %><br>
    <%= f.text_field :minPrice %>
  </div>
  <div class="field">
    <%= f.label :maxPrice %><br>
    <%= f.text_field :maxPrice %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br>
    <%= f.text_area :keywords %>
  </div>
  <div class="field">
    <%= f.label :categoryURL %><br>
    <%= f.text_field :categoryURL %>
  </div>
  <div class="field">
    <%= f.label :listingIDs %><br>
    <%= f.text_area :listingIDs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PhantomCraigslistCrawler_Ruby/Version 2/app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

PhantomCraigslistCrawler_Ruby/Version 2/app/views/searches/index.html.erb
<h1>Listing searches</h1>

<table>
  <thead>
    <tr>
      <th>Userids</th>
      <th>Minprice</th>
      <th>Maxprice</th>
      <th>Keywords</th>
      <th>Categoryurl</th>
      <th>Listingids</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.userIDs %></td>
        <td><%= search.minPrice %></td>
        <td><%= search.maxPrice %></td>
        <td><%= search.keywords %></td>
        <td><%= search.categoryURL %></td>
        <td><%= search.listingIDs %></td>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

PhantomCraigslistCrawler_Ruby/Version 2/app/views/searches/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

PhantomCraigslistCrawler_Ruby/Version 2/app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userids:</strong>
  <%= @search.userIDs %>
</p>

<p>
  <strong>Minprice:</strong>
  <%= @search.minPrice %>
</p>

<p>
  <strong>Maxprice:</strong>
  <%= @search.maxPrice %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @search.keywords %>
</p>

<p>
  <strong>Categoryurl:</strong>
  <%= @search.categoryURL %>
</p>

<p>
  <strong>Listingids:</strong>
  <%= @search.listingIDs %>
</p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>

PhantomCraigslistCrawler_Ruby/Version 2/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :homeURL %><br>
    <%= f.text_field :homeURL %>
  </div>
  <div class="field">
    <%= f.label :subURL %><br>
    <%= f.text_field :subURL %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PhantomCraigslistCrawler_Ruby/Version 2/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

PhantomCraigslistCrawler_Ruby/Version 2/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Homeurl</th>
      <th>Suburl</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstName %></td>
        <td><%= user.lastName %></td>
        <td><%= user.email %></td>
        <td><%= user.homeURL %></td>
        <td><%= user.subURL %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<br><br>
<%= link_to 'Home', root_path %>

PhantomCraigslistCrawler_Ruby/Version 2/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

PhantomCraigslistCrawler_Ruby/Version 2/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastName %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Homeurl:</strong>
  <%= @user.homeURL %>
</p>

<p>
  <strong>Suburl:</strong>
  <%= @user.subURL %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>