SolicitationManager_Ruby/config/routes.rb
SolicitationManager::Application.routes.draw do
  resources :terms

  resources :requirements

  resources :items

  root :to => 'home#index'
  
  resources :solicitations

  

end

SolicitationManager_Ruby/app/models/requirement.rb
class Requirement < ActiveRecord::Base
end

SolicitationManager_Ruby/app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController
  before_action :set_requirement, only: [:show, :edit, :update, :destroy]

  # GET /requirements
  # GET /requirements.json
  def index
    @requirements = Requirement.all
  end

  # GET /requirements/1
  # GET /requirements/1.json
  def show
  end

  # GET /requirements/new
  def new
    @requirement = Requirement.new
  end

  # GET /requirements/1/edit
  def edit
  end

  # POST /requirements
  # POST /requirements.json
  def create
    @requirement = Requirement.new(requirement_params)

    respond_to do |format|
      if @requirement.save
        format.html { redirect_to @requirement, notice: 'Requirement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @requirement }
      else
        format.html { render action: 'new' }
        format.json { render json: @requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requirements/1
  # PATCH/PUT /requirements/1.json
  def update
    respond_to do |format|
      if @requirement.update(requirement_params)
        format.html { redirect_to @requirement, notice: 'Requirement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requirements/1
  # DELETE /requirements/1.json
  def destroy
    @requirement.destroy
    respond_to do |format|
      format.html { redirect_to requirements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_requirement
      @requirement = Requirement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def requirement_params
      params.require(:requirement).permit(:buy_num, :title, :specification)
    end
end

SolicitationManager_Ruby/app/helpers/requirements_helper.rb
module RequirementsHelper
end

SolicitationManager_Ruby/app/views/requirements/_form.html.erb
<%= form_for(@requirement) do |f| %>
  <% if @requirement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@requirement.errors.count, "error") %> prohibited this requirement from being saved:</h2>

      <ul>
      <% @requirement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :buy_num %><br>
    <%= f.text_field :buy_num %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :specification %><br>
    <%= f.text_area :specification %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SolicitationManager_Ruby/app/views/requirements/edit.html.erb
<h1>Editing requirement</h1>

<%= render 'form' %>

<%= link_to 'Show', @requirement %> |
<%= link_to 'Back', requirements_path %>

SolicitationManager_Ruby/app/views/requirements/index.html.erb
<h1>Listing requirements</h1>

<table>
  <thead>
    <tr>
      <th>Buy num</th>
      <th>Title</th>
      <th>Specification</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @requirements.each do |requirement| %>
      <tr>
        <td><%= requirement.buy_num %></td>
        <td><%= requirement.title %></td>
        <td><%= requirement.specification %></td>
        <td><%= link_to 'Show', requirement %></td>
        <td><%= link_to 'Edit', edit_requirement_path(requirement) %></td>
        <td><%= link_to 'Destroy', requirement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Requirement', new_requirement_path %>

SolicitationManager_Ruby/app/views/requirements/new.html.erb
<h1>New requirement</h1>

<%= render 'form' %>

<%= link_to 'Back', requirements_path %>

SolicitationManager_Ruby/app/views/requirements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Buy num:</strong>
  <%= @requirement.buy_num %>
</p>

<p>
  <strong>Title:</strong>
  <%= @requirement.title %>
</p>

<p>
  <strong>Specification:</strong>
  <%= @requirement.specification %>
</p>

<%= link_to 'Edit', edit_requirement_path(@requirement) %> |
<%= link_to 'Back', requirements_path %>